"""modify review image column

Revision ID: 49d7c16f76a3
Revises: a63d1af8e580
Create Date: 2023-04-25 01:57:51.388827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49d7c16f76a3'
down_revision = 'a63d1af8e580'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_images', schema=None) as batch_op:
        batch_op.alter_column('review_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_images', schema=None) as batch_op:
        batch_op.alter_column('review_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
