"""add preview column

Revision ID: a63d1af8e580
Revises: f9cf20032b54
Create Date: 2023-04-25 00:37:42.815387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a63d1af8e580'
down_revision = 'f9cf20032b54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preview', sa.Boolean(), nullable=False))

    with op.batch_alter_table('review_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preview', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_images', schema=None) as batch_op:
        batch_op.drop_column('preview')

    with op.batch_alter_table('restaurant_images', schema=None) as batch_op:
        batch_op.drop_column('preview')

    # ### end Alembic commands ###
